### ISSUE TITLE
1.22.0 broke existing code type check

### ISSUE THREAD

**Issue by EdJoPaTo** [grammyjs/grammY#562]
Existing code stopped working with 1.22.0, to be exact #553.

```typescript
bot.on(
	'edited_message',
	async ctx =>
		ctx.reply(
			'Edited!',
			{reply_to_message_id: ctx.editedMessage.message_id},
		),
);
```

```plaintext
error TS18048: 'ctx.editedMessage' is possibly 'undefined'.
```

This looks like a mistake and should be fixed.

**Comment by AB-70** [comment]
Facing the same issue after updating.

**Comment by KnorpelSenf** [comment]
I am waiting for a review of #555.

**Comment by KnorpelSenf** [comment]
#555 was merged and fixed this

**Comment by KnorpelSenf** [comment]
Fascinating, investigating
